In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s5e6/sample_submission.csv
/kaggle/input/playground-series-s5e6/train.csv
/kaggle/input/playground-series-s5e6/test.csv

In [3]:
df_sample = pd.read_csv('/kaggle/input/playground-series-s5e6/sample_submission.csv')
df_train = pd.read_csv('/kaggle/input/playground-series-s5e6/train.csv')
df_test = pd.read_csv('/kaggle/input/playground-series-s5e6/test.csv')

In [4]:
df_train.head()

,id,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,0,37,70,36,Clayey,Sugarcane,36,4,5,28-28
1,1,27,69,65,Sandy,Millets,30,6,18,28-28
2,2,29,63,32,Sandy,Millets,24,12,16,17-17-17
3,3,35,62,54,Sandy,Barley,39,12,4,10-26-26
4,4,35,58,43,Red,Paddy,37,2,16,DAP

In [5]:
df_test.head()

,id,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous
0,750000,31,70,52,Sandy,Wheat,34,11,24
1,750001,27,62,45,Red,Sugarcane,30,14,15
2,750002,28,72,28,Clayey,Ground Nuts,14,15,4
3,750003,37,53,57,Black,Ground Nuts,18,17,36
4,750004,31,55,32,Red,Pulses,13,19,14

In [6]:
df_train['Fertilizer Name'].value_counts()

Fertilizer Name
14-35-14    114436
10-26-26    113887
17-17-17    112453
28-28       111158
20-20       110889
DAP          94860
Urea         92317
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import OneHotEncoder

enc_soil_type = OneHotEncoder()
enc_soil_type.fit_transform(df_train['Soil Type'])

enc_crop_type = OneHotEncoder()
enc_crop_type.fit_transform(df_train['Crop Type'])

enc_fertilizer_name = OneHotEncoder()
enc_fertilizer_name.fit_transform(df_train['Fertilizer Name'])

In [ ]:
def preprocessing(df):
    df = df.copy()
    df = df.drop(columns=['id'])
    df.columns = df.columns.str.lower().str.replace(' ', '_')

    df['soil_type'] = enc_soil_type.transform(df['soil_type'])
    df['crop_type'] = enc_crop_type.transform(df['crop_type'])
    if 'fertilizer_name' in df.columns:
        df['fertilizer_name'] = enc_fertilizer_name.transform(df['fertilizer_name'])

    return df

y = preprocessing(df_train)['fertilizer_name'].values
X = preprocessing(df_train).drop(columns=['fertilizer_name']).values
X_test = preprocessing(df_test)

In [ ]:
X_train

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_val, y_train, y_val = train_test_split(X, y, random_state=42)

scaler = StandardScaler()
scaler.fit_transform(X_train)
scaler.transform(X_val)

In [ ]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(multi)